file=open("a.txt","r")
#print(file.read())
file.close()
file=open("a.txt","r")
print("\n Read in parts \n")
#print(file.read(98))
file.close()
file=open("a.txt","w")
file.write("Hi I am Saadiq & I am 11 years old")
file.close()
file=open("a.txt","r")
print(file.read())